name: restaurant_order_system
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.0.1
  path: ^1.9.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/menus/

  fonts:
    - family: Istok Web
      fonts:
        - asset: assets/fonts/IstokWeb-Regular.ttf
          weight: 400
        - asset: assets/fonts/IstokWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/IstokWeb-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/IstokWeb-BoldItalic.ttf
          weight: 700
          style: italic
